# Generated by Django 4.2.7 on 2025-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
