# Generated by Django 4.2.7 on 2025-05-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_variantitem_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Course Module'},
        ),
        migrations.AlterModelOptions(
            name='variantitem',
            options={'verbose_name': 'Course Lession'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.FloatField(default=0.0, help_text='Supports ordering like 1, 1.1, 1.2 etc.'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='flat_discount',
            field=models.FloatField(default=2500, help_text='Amount'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='order',
            field=models.FloatField(default=0.0, help_text='Supports ordering like 1, 1.1, 1.2 etc.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.FloatField(default=0.0, help_text='Supports ordering like 1, 1.1, 1.2 etc.'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='order',
            field=models.FloatField(default=0.0, help_text='Supports ordering like 1, 1.1, 1.2 etc.'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionanswermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questionanswermessage',
            name='order',
            field=models.FloatField(default=0.0, help_text='Supports ordering like 1, 1.1, 1.2 etc.'),
        ),
        migrations.AddField(
            model_name='questionanswermessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='order',
            field=models.FloatField(default=0.0, help_text='Supports ordering like 1, 1.1, 1.2 etc.'),
        ),
        migrations.AddField(
            model_name='variant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='order',
            field=models.FloatField(default=0.0, help_text='Supports ordering like 1, 1.1, 1.2 etc.'),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='category.jpg', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=1, help_text='Pecentage'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.CharField(blank=True, help_text='Introduction Video', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', help_text='Course Feature Image', null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.CharField(blank=True, help_text='Video File URL', max_length=200, null=True),
        ),
    ]
