# Generated by Django 4.2.7 on 2025-05-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coupon_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='related_courses',
            field=models.ManyToManyField(blank=True, help_text='Manually select related courses', related_name='related_to', to='api.course'),
        ),
    ]
